=== AlexisAmand/Boitasite/selfhtml/xml/dtd/affichage/adresses.dtd
<!ELEMENT adresses (adresse)*>

<!ELEMENT adresse (titre?, nom, (boite_postale | numero_rue), codepostal_ville)>

<!ELEMENT titre (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT boite_postale (#PCDATA)>
<!ELEMENT numero_rue (#PCDATA)>
<!ELEMENT codepostal_ville (#PCDATA)>

=== AlexisAmand/Boitasite/selfhtml/xml/dtd/affichage/adresses.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE adresses SYSTEM "adresses.dtd">
<adresses>
<adresse>
  <nom>Société Générale</nom>
  <boite_postale>7001</boite_postale>
  <codepostal_ville>13100 Aix en Provence</codepostal_ville>
</adresse>
<adresse>
  <titre>Monsieur</titre>
  <nom>Luc Minighetti</nom>
  <numero_rue>112 rue de Lyon</numero_rue>
  <codepostal_ville>13000 Marseille</codepostal_ville>
</adresse>
</adresses>
