=== AlexisAmand/Boitasite/selfhtml/xml/dtd/affichage/fichier_personnel.dtd
<!ELEMENT fichier_personnel          (personne)*>
<!ELEMENT personne          (bio,socio)>
<!ATTLIST personne
   nom                   CDATA #REQUIRED
>
<!ELEMENT bio             (yeux,cheveux,peau,poids,groupe_sanguin)>
<!ELEMENT yeux           EMPTY>
<!ATTLIST yeux
   couleur                  CDATA #REQUIRED
>
<!ELEMENT cheveux            EMPTY>
<!ATTLIST cheveux
   couleur                  CDATA #REQUIRED
   remarque              CDATA #IMPLIED
>
<!ELEMENT peau            EMPTY>
<!ATTLIST peau
   couleur                  CDATA #REQUIRED
   remarque              CDATA #IMPLIED
>
<!ELEMENT poids         EMPTY>
<!ATTLIST poids
   kg                     CDATA #REQUIRED
>
<!ELEMENT groupe_sanguin      EMPTY>
<!ATTLIST groupe_sanguin
   type                    (A|B|0|AB) #REQUIRED
>
<!ELEMENT socio           (langue,etat_civil,passeport)>
<!ELEMENT langue         EMPTY>
<!ATTLIST langue
   lang                   CDATA #REQUIRED
   abr                   (de|en|fr|es|pt|it) #IMPLIED
>
<!ELEMENT etat_civil           EMPTY>
<!ATTLIST etat_civil
   type                    (celibataire|marie|veuf) #REQUIRED
>
<!ELEMENT passeport        EMPTY>
<!ATTLIST passeport
   nr                     NMTOKEN #REQUIRED
>

=== AlexisAmand/Boitasite/selfhtml/xml/dtd/affichage/fichier_personnel.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE fichier_personnel SYSTEM "fichier_personnel.dtd">
<fichier_personnel>
<personne nom="Prosper Têtedeuf">
  <bio>
    <yeux couleur="bleugris" />
    <cheveux couleur="blonds" remarque="parfois teints" />
    <peau couleur="blanche" />
    <poids kg="74" />
    <groupe_sanguin type="A" />
  </bio>
  <socio>
    <langue lang="française" abr="fr" />
    <etat_civil type="marie" />
    <passeport no="38385409398" />
  </socio>
</personne>
</fichier_personnel>
