=== AlexisAmand/Boitasite/selfhtml/xml/dtd/affichage/livre.dtd
<!ENTITY % texte "rehausse | remarque | exigeant | passage_ligne">

<!ELEMENT livre                   (titre,informations,index_contenu,(chapitre)+,index_motscles)>

<!ELEMENT titre                  (titre_principal,soustitre)>
<!ELEMENT titre_principal             (#PCDATA)>
<!ELEMENT soustitre             (#PCDATA)>

<!ELEMENT informations              (cip,copyright,editeur)>
<!ELEMENT cip                    (#PCDATA | %texte;)*>
<!ELEMENT droits_auteur              (#PCDATA | %texte;)*>
<!ELEMENT editeur                 (#PCDATA | %texte;)*>

<!ELEMENT index_contenu     (titre_ic,(mentionchap_ic | mentionsection_ic)*)>
<!ELEMENT titre_ic       (#PCDATA)>
<!ELEMENT mentionchap_ic     (#PCDATA)>
<!ELEMENT mentionsection_ic  (#PCDATA)>

<!ELEMENT chapitre                (titre_chapitre,(section)+)>
<!ELEMENT titre_chapitre       (#PCDATA)>

<!ELEMENT section              (titre_section,(texte_courant | enumeration | graphique)+)>
<!ELEMENT titre_section        (#PCDATA)>

<!ELEMENT texte_courant             (#PCDATA | %texte;)*>
<!ELEMENT enumeration            (point_enumeration)+>
<!ELEMENT point_enumeration      (#PCDATA | %texte;)*>
<!ELEMENT graphique                 (fichier_graphique)>
<!ELEMENT fichier_graphique            (#PCDATA)>

<!ELEMENT index_motscles   (titre_imc,(mention_imc)*)>
<!ELEMENT titre_imc       (#PCDATA)>
<!ELEMENT mention_imc            (#PCDATA)>

<!ELEMENT rehausse          (#PCDATA)>
<!ELEMENT remarque             (#PCDATA)>
<!ELEMENT exigeant            (#PCDATA)>
<!ELEMENT passage_ligne          EMPTY>

=== AlexisAmand/Boitasite/selfhtml/xml/dtd/affichage/livre.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE livre SYSTEM "livre.dtd">
<?xml:stylesheet type="text/css" href="livre.css" ?>

<livre>

<titre>
<titre_principal>Je suis Valentin</titre_principal>
<soustitre>Comment ma vie est devenue ce qu'elle est</soustitre>
</titre>

<informations>
<cip>Bibliothèque nationale de France - CIP-Einheitsaufnahme:<passage_ligne />
Titeldatensatz disponible à la  bibliothèque nationale de France</cip>
<droits_auteur>©2000 tous droits réservés chez l'éditeur</droits_auteur>
<editeur>Mon édition, Derrière la rotonde</editeur>
</informations>

<index_contenu>
<titre_ic>index_contenu</titre_ic>

<mentionchap_ic>Mes jeunes années</mentionchap_ic>
<mentionsection_ic>enfance</mentionsection_ic>
<mentionsection_ic>jeunesse</mentionsection_ic>

<mentionchap_ic>Comment je suis devenu un homme</mentionchap_ic>
<mentionsection_ic>Le premier amour</mentionsection_ic>

</index_contenu>

<chapitre>
<titre_chapitre>Mes jeunes années</titre_chapitre>

<section>
<titre_section>Enfance</titre_section>

<texte_courant>
Mon enfance comprend deux sections de m vie:
</texte_courant>

<enumeration>
<point_enumeration>- l'âge du nourrisson</point_enumeration>
<point_enumeration>- l'âge du garçonnet</point_enumeration>
</enumeration>

</section>

<section>
<titre_section>Jeunesse</titre_section>

<texte_courant>Ma jeunesse se résume pour l'essentiel à l'acné juvénile.
</texte_courant>

</section>

</chapitre>

<chapitre>
<titre_chapitre>Comment je suis devenu un homme</titre_chapitre>

<section>
<titre_section>Le premier amour</titre_section>

<texte_courant>Sie <rehausse>surgit</rehausse>, <rehausse>se vécut</rehausse>, et <rehausse>s'en fut</rehausse> à nouveau.
</texte_courant>

<graphique>
<fichier_graphique>premieramour.tif</fichier_graphique>
</graphique>

</section>

</chapitre>

<index_motscles>
<titre_imc>Index des mots clé</titre_imc>

<mention_imc>acné</mention_imc>
<mention_imc>amour</mention_imc>
<mention_imc>enfance</mention_imc>
<mention_imc>jeunesse</mention_imc>
<mention_imc>nourisson</mention_imc>

</index_motscles>

</livre>
