=== AlexisAmand/Boitasite/selfhtml/xml/dtd/affichage/recettes.dtd
<!ELEMENT recettes (liste_ingredients, suite_instructions)>

<!ELEMENT liste_ingredients (ingredient)+>
<!ELEMENT ingredient (#PCDATA)>

<!ELEMENT suite_instructions (instruction)*>
<!ELEMENT instruction (#PCDATA)>

=== AlexisAmand/Boitasite/selfhtml/xml/dtd/affichage/recettes.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE recettes SYSTEM "recettes.dtd">
<recettes>
  <liste_ingredients>
     <ingredient>300 g  pommes de terre épluchées</ingredient>
     <ingredient>2  poireaux</ingredient>
     <ingredient>1 oignon</ingredient>
     <ingredient>1 tb beurre</ingredient>
     <ingredient>600 ml eau</ingredient>
  </liste_ingredients>
  <suite_instructions>
     <instruction>couper les pommes de terre en petits dès.</instruction>
     <instruction>laver les poireaux,les couper en fines rondelles.</instruction>
     <instruction>éplucher l'oignon, le couper fin et le faire réduire au beurre.</instruction>
     <instruction>ajouter les pommes de terre, les poireaux et l'eau et cuire 18 à 20 minutes.</instruction>
  </suite_instructions>
</recettes>
