=== AlexisAmand/Boitasite/selfhtml/xml/dtd/affichage/stock.dtd
<!ENTITY % article "numero_article, nom_article, quantite_article">
<!ENTITY % additif "description | classe_produit">
<!ELEMENT stock (entree | sortie)*>
<!ELEMENT entree (numero_entree, (%article;), (%additif;))>
<!ELEMENT sortie (numero_sortie, (%article;), (%additif;))>
<!ELEMENT numero_entree (#PCDATA)>
<!ELEMENT numero_sortie (#PCDATA)>
<!ELEMENT numero_article  (#PCDATA)>
<!ELEMENT nom_article    (#PCDATA)>
<!ELEMENT quantite_article   (#PCDATA)>
<!ELEMENT description   (#PCDATA)>
<!ELEMENT classe_produit    (#PCDATA)>

=== AlexisAmand/Boitasite/selfhtml/xml/dtd/affichage/stock.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE stock SYSTEM "stock.dtd">
<stock>

<entree>
  <numero_entree>452</numero_entree>
  <numero_article>45-234</numero_article>
  <nom_article>fauteuil de bureau "ministre"</nom_article>
  <quantite_article>10</quantite_article>
  <classe_produit>C-III</classe_produit>
</entree>
<sortie>
  <numero_sortie>318</numero_sortie>
  <numero_article>37-917</numero_article>
  <nom_article>armoire à glaces  "Narcisse"</nom_article>
  <quantite_article>3</quantite_article>
  <description>F-IV</description>
</sortie>

</stock>
