=== AlexisAmand/Boitasite/selfhtml/xml/representation/affichage/produktnews.dtd
<!ELEMENT nouveautes (#PCDATA | description)*>
<!ELEMENT description (#PCDATA | fabricant | produit | prix)*>
<!ELEMENT fabricant (#PCDATA)>
<!ELEMENT produit (#PCDATA)>
<!ELEMENT prix (#PCDATA)>

=== AlexisAmand/Boitasite/selfhtml/xml/representation/affichage/produktnews.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE nouveautes SYSTEM "produktnews.dtd">
<?xml-stylesheet type="text/xsl" href="produktnews.xsl" ?>
<nouveautes>

Les derniers messages de nouveautés :

<description>
La firme  <fabricant>Logimages</fabricant> a sorti une nouvelle version du jeu populaire
de ballon <produit>Manette chaude</produit>.
D'après les renseignements fournis par le constructeur, la nouvelle version qui fonctionne aussi sous le système d'exploitation <produit>sans plantage</produit> devrait coûter aux alentours de <prix>80 Euros</prix>.
</description>

<description>
Il existe maintenant une rustine de <fabricant>Logicycles SARL Inc.</fabricant> pour le CD ROM de colllection
<produit>Florilège d'idées d'autrui</produit>. Il était de notoriété publique que quelques uns des modèles de pages Web sensationnelles contenaient encore par erreur des mentions des auteurs originaux. La rustine est maintenant offerte pour le prix ridicule de  <prix>200 Euros</prix>.
</description>

</nouveautes>
